# Generated by Django 3.0.6 on 2020-05-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityRecord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tz',
            field=models.CharField(default='Asia/kolkata', max_length=100),
        ),
    ]
